name: Generate Snake Animation

on:
  push:
    branches:
      - main  
  schedule:
    - cron: "0 0 * * *"  # Runs daily to update the snake

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: helllopratik  
          outputs: dist/snake.svg

      - name: Upload the snake animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg

      - name: Push to repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output

